version: '3'
services:
  web:
    image: nginx:1.16.0
    ports:
      - "9001:9001"
    depends_on:
      - app
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html/
  app:
    build: ./docker/php
    depends_on:
    - mysql
    volumes:
      - .:/var/www/html
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: river_db
      MYSQL_USER: root
      MYSQL_PASSWORD: river@123
      MYSQL_ROOT_PASSWORD: river@123
    ports:
      - "13306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
